### ISSUE TITLE
[BUG] Rectangular mounts not calculated constrained movement of riders correctly

### ISSUE THREAD

**Issue by galaara98** [p4535992/foundryvtt-mountup#15]
**Module Version:** MountUP: v3.2.24, TA: 4.4.5, TokenZ: 0.6.5, LibWrapper 0.8.0 

**Describe the bug**
When a rider is smaller in grid units than a mount, there is a wonderful feature that allows constrained movement on the mount itself.
There is a bug when a mount in not a square grid shape, where if the mount is rotated, the constrained movement is allowed in the original shape of the token and not the rotated state.  

**To Reproduce**

1. Create an actor token "the mount" whose grid shape is 3x5 [i used a vehicle actor in PF2E system, and then set the length to 25 and the width to 15 (in this case a BOAT)].  NOTE: as far as I know FoundryVTT will never let you make a token that does not have a rectangular shape.. this bug is just referencing when a shape is rectangular, but not square.
2. Create an actor token "the rider" whose gride shape is 1x1 [i used a player character in PF2E system who was size medium]
3. Get both tokens onto a scene
4. Mount up the Rider to the Mount via MountUp module
5. Move the rider around the 3x5 mount and everything works as expected.
6. Move the rider to the top right corner grid on the mount (x=1,y=1 of the mount)
7. Rotate the mount 90 degrees, causing the mount to have a shape that is 5x3 [at least visually] 
(Mount up and Token Attacher work wonderfully calculating where the rider should be)
8. now move the rider around the mount (you will notice that it can only be moved to areas represented by the original shape and you cannot move it back to the location it started at when step 8 began)

**Expected behavior**
The constrained movement grid should match the new shape of "The Mount"
it would be great if the grid would calculate on 0, 45, 90,135 (and all of their mirrors 0 is the same as 180, 45 is the same as 225, 90 is the same as 270, 135 is the same as 315) to determine where the rider can go on the mount,   (where 0 represents any rotation from 338.01 to 23 degrees (338.01-359.99 and 0-23), 45 represents any rotation from 23.01 to 68 degrees, 90 represents any rotation from 68.01 to 113, and 135 represents any rotation from 113.01 to 158 ... etc)

BUT if calculating the appropriate grid would be overly complicated at non-right angles, then it would still be beneficial if the grid was calculated 

1. as "Normal" when the mount rotation is between 315-45 (315-359.99 or 0-45) or 135-225, 
2. or calculated it as "Turned Sideways" when not (causing the grid that the rider can move around in to be the shape of Y,X of the mounts grid units)

**Screenshots**

**Browser:**
 M$ Edgium 103.0.1264.44

**Foundry Version:**
9.269

**Game System:** 
PF2e 3.12.2.10

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by p4535992** [comment]
# THIS MODULES IS DEPRECATED ON V11 IN FAVOR OF [Rideable](https://foundryvtt.com/packages/rideable)
