### ISSUE TITLE
Mount Deletes Multiple Riders when removing a single one

### ISSUE THREAD

**Issue by Jacob-Lisner** [p4535992/foundryvtt-mountup#19]
This line of code at line 174 in mountManager.ts:

riders.splice(riders.indexOf(riderToken.id));

causes the mount to erroneously remove multiple riders when dismounting a single rider. You can do this by:

1. Mounting multiple riders to a single token
2. Removing any rider that wasn't the last one

It can be fixed by replacing the above line with:

riders.splice(riders.indexOf(riderToken.id), 1);

**Comment by p4535992** [comment]
TY VERY MUCH, sorry for the late reply, will be fixed in the next release
