### ISSUE TITLE
[BUG] When mounting using the 'drag and drop' option, the pop-up message asking for a confirmation does not appear.

### ISSUE THREAD

**Issue by nirurin** [p4535992/foundryvtt-mountup#20]
**Module Version:** v3.3.5

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
When mounting using the 'drag and drop' option, the pop-up message asking for a confirmation does not appear. It does seem to automatically attach the rider to the mount, but the movement is a bit broken (they detach and move disconnectedly. 

[Video4.webm](https://user-images.githubusercontent.com/3751273/213585009-8293d6a2-82b1-4eff-bc91-ff3d6910ec44.webm)

**To Reproduce**
1. Make an actor
2. Make a horse
3. Drag actor onto horse
4. See broken

**Expected behavior**
A pop-up confirmation is meant to appear isn't it? Plus the movement should work the same as the normal 'click icon to mount' behaviour (which works fine)

**Screenshots**
[Video4.webm](https://user-images.githubusercontent.com/3751273/213585009-8293d6a2-82b1-4eff-bc91-ff3d6910ec44.webm)

**Browser:**
Foundry app, chrome and edge. 

 - 

**Foundry Version:** 
10.291

**Game System:** 
Dnd 2.1.2

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by p4535992** [comment]
# THIS MODULES IS DEPRECATED ON V11 IN FAVOR OF [Rideable](https://foundryvtt.com/packages/rideable)
