### ISSUE TITLE
Option to move the mount when moving the token

### ISSUE THREAD

**Issue by DawidIzydor** [p4535992/foundryvtt-mountup#21]
In some cases, like when both mount and the rider have the same token size, it's not intuitive how to move the mount that is below it's rider. It'd be useful to have an option to move the mount when moving rider, now we only have the other way around - move rider when moving mount. I suggest to add a dropdown with the default setting being the current one, and the new feature being the optional one

**Comment by p4535992** [comment]
# THIS MODULES IS DEPRECATED ON V11 IN FAVOR OF [Rideable](https://foundryvtt.com/packages/rideable)
