### ISSUE TITLE
Selected GM NPC tokens move with PC Mounted tokens

### ISSUE THREAD

**Issue by kozmo199** [p4535992/foundryvtt-mountup#8]
In order to submit an effective bug report, please include the following information along with your issue description.

### Environment Details

> Please share the following basic details about your setup.

* Foundry VTT Version: 9.255
* Operating System: Windows 10
* How Are You Using Foundry: Native Application (GM) and Chrome (PCs)
* Which Game System: dnd5e 1.5.7
* Modules Enabled?: Yes

Active Modules:
----------
Advanced Macros v;
Better Roll Tables v;
Cautious Gamemaster's Pack v;
Combat Enhancements v;
Combat Ready! v;
Combat Ready! Themes Pack v;
Combat Utility Belt v;
Compendium Folders v;
D&D Beyond Importer v;
DFreds Droppables v;
Dice So Nice! v;
Dice Tray v;
Drag Ruler v;
Drag Upload (Get Over Here!) v;
EasyTable by Blitz v;
Foundry Community Tables v;
FoundryVTT Mount Up! v;
FXMaster v;
GM Notes v;
GM Token-Drag Visibility v2 v;
Hey, Wait! v;
Initiative Double Click v;
Less Fog v;
lib - Color Settings v;
Library: Scene Packer v;
libWrapper v0;
Midi QOL v;
Multilevel Tokens v;
Not Your Turn! v;
Patrol v;
Perfect Vision v;
Plutonium v;
PnP - Pointer and Pings! v;
Quick Insert - Search Widget v;
Sane Magical Item Prices Compendium v;
Scene Transitions v;
Simple Calendar v;
socketlib v;
Split Journal v;
Tabletop RPG Music v;
The Furnace v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Token Action HUD v;
Token Attacher v;
Token Info Icons v;
Tokenizer v;
Token Mold v;
Token Z v;
Torch v;
Universal Battlemap Importer v;
Waterdeep - City of Splendors v;
Weather Control v;
World Anvil Integration v;
World Anvil Integration - Actors v;
World Anvil Integration - Custom secrets v;

Inactive Modules:
----------

### Issue Description

> Please provide a description of your issue below. Including console error messages, screenshots or videos can be particularly helpful.

This bug appears to be the following:

When a Player Character with control of a mounted token (e.g. their Paladin character mounted onto a Warhorse) moves their grouped tokens, it moves them on the map as expected. However, if I as the GM also have an enemy NPC token selected on the screen (orange box around them) while this movement happens, it moves that NPC token (which the Player character does NOT own and cannot move) in the exact same way - e.g. if the player moves down 3 squares and over 2, the NPC token mirrors the exact same move. If I as the GM unselect all tokens on the screen on my view, nothing moves other than the Player Character + mount when the PC makes their movement.

It only seems to happen with the 2 PCs that are using MountUp on their tokens, which leads me to believe it is tied to this module's movement attaching behavior.

**Comment by p4535992** [comment]
# THIS MODULES IS DEPRECATED ON V11 IN FAVOR OF [Rideable](https://foundryvtt.com/packages/rideable)
